### ISSUE TITLE
9.c

### ISSUE THREAD

**Issue by wongziihou** [wongziihou/example#1]
why my 9.c worked 2 times when i entered a number ？and how to correct?
为什么我输入1个数字，会进行两次printf？
随便帮我看看有没有英语语病。

**Comment by wongzigii** [comment]
Actually, you are entering two character, a number letter and a `new line character`, which return by ENTER key.  `%c` is a char format in C language. The first printf is what you input firstly, and the second printf is always `10`, which 10 is represented for a new line character .aka. `\n` in ASCII. 

https://en.wikipedia.org/wiki/ASCII

**Comment by wongziihou** [comment]
So,how can  i cancel the second printf ? I just wanna enter a character and  it return a number.

**Comment by wongziihou** [comment]
这是一个无线循环的程序，那我应该怎么终止？

**Comment by wongzigii** [comment]
按 Ctrl + C 终止

**Comment by wongzigii** [comment]
把 %c 改成其他类型

**Comment by wongziihou** [comment]
如果我换成％d，可以达到我想要的效果，但是xcode会有⚠️。！所以我还应该怎么改？

**Comment by wongziihou** [comment]
我再尝试了一次我写的程序，我发现不用改％c，程序也已经和我想要的一样了。

**Comment by wongzigii** [comment]
OK. Close this issue.

**Comment by wongziihou** [comment]
wait for a minute ,我改进了一点，when i press control + c,the program will have a infinite loop

**Comment by wongziihou** [comment]
@wongzigii

**Comment by wongziihou** [comment]
why it will have a infinite loop

**Comment by wongzigii** [comment]
`while (scanf("%c",&A))`
